In [1]:
import pandas as pd

file_path = '/home/btech/ayush.singh/HSN/tune_diffusion/examples/dreambooth/data.csv'
df = pd.read_csv(file_path)


# Step 3: Filter the DataFrame to select all rows with the desired value
filtered_data = df[df['Dataset_Name'] == 'clock']
filtered_data = filtered_data[filtered_data['diffusion_ver'] == 'sdxl']
sorted_df = filtered_data.sort_values(by='clipi', ascending=False)

# Step 4: Display the filtered data
print(sorted_df)

     Dataset_Name diffusion_ver Adaptor  lora_rank     clipi     clipt  \
1629        clock          sdxl    lora          8  0.806641  0.278473
1908        clock          sdxl   krona          4  0.803711  0.293897
350         clock          sdxl   krona          4  0.792969  0.291901
1375        clock          sdxl    lora         16  0.791992  0.295628
1260        clock          sdxl    lora         16  0.791504  0.305525
...           ...           ...     ...        ...       ...       ...
1640        clock          sdxl    lora          8  0.568359  0.197771
1711        clock          sdxl    lora          4  0.566895  0.205148
1635        clock          sdxl    lora          8  0.565430  0.195182
1713        clock          sdxl    lora          4  0.561523  0.203282
1633        clock          sdxl    lora          8  0.552246  0.218497

      num_train_steps  no_of_images  learning_rate  \
1629              800             6        0.00090
1908              500             6        0.00040
350              1200             6        0.00010
1375              400             6        0.00005
1260              400             6        0.00010
...               ...           ...            ...
1640              800             6        0.00100
1711              800             6        0.00090
1635             1200             6        0.00090
1713             1000             6        0.00090
1633             1000             6        0.00090

                                            output_path  \
1629  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1908  /home/btech/ayush.singh/outputs_sdxl/clock/kro...
350   /home/btech/ayush.singh/outputs_sdxl/clock/kro...
1375  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1260  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
...                                                 ...
1640  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1711  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1635  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1713  /home/btech/ayush.singh/outputs_sdxl/clock/lor...
1633  /home/btech/ayush.singh/outputs_sdxl/clock/lor...

      with_prior_preservation
1629                    False
1908                    False
350                     False
1375                    False
1260                    False
...                       ...
1640                    False
1711                    False
1635                    False
1713                    False
1633                    False

[305 rows x 11 columns]

In [2]:


sorted_df = filtered_data.sort_values(by='clipt', ascending=False)
sorted_df

,Dataset_Name,diffusion_ver,Adaptor,lora_rank,clipi,clipt,num_train_steps,no_of_images,learning_rate,output_path,with_prior_preservation
357,clock,sdxl,krona,4,0.726562,0.326826,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
413,clock,sdxl,krona,4,0.730957,0.326712,1000,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
51,clock,sdxl,krona,8,0.729980,0.326486,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
718,clock,sdxl,krona,16,0.727051,0.326355,800,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
120,clock,sdxl,krona,8,0.722656,0.326181,1200,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False
...,...,...,...,...,...,...,...,...,...,...,...
1715,clock,sdxl,lora,4,0.626465,0.201726,1200,6,0.000900,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
1702,clock,sdxl,lora,4,0.636719,0.199354,800,6,0.000800,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
1640,clock,sdxl,lora,8,0.568359,0.197771,800,6,0.001000,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
1695,clock,sdxl,lora,4,0.631348,0.197335,1000,6,0.000700,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False
1635,clock,sdxl,lora,8,0.565430,0.195182,1200,6,0.000900,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False

In [3]:
columns_to_normalize = ['clipi', 'clipt']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sorted_df[columns_to_normalize] = scaler.fit_transform(sorted_df[columns_to_normalize])

# Step 4: Calculate a new column 'Normalised' by summing the normalized values of the selected columns
sorted_df['Normalised'] = sorted_df[columns_to_normalize].sum(axis=1)

# Step 5: Sort the DataFrame based on the 'Normalised' column in descending order
sorted_df = sorted_df.sort_values(by='Normalised', ascending=False)

# Step 6: Display the sorted DataFrame
print(sorted_df['Normalised'])

721     1.796192
1260    1.778690
763     1.747376
1344    1.742817
1908    1.738351
          ...
1633    0.177110
1711    0.133287
1713    0.098000
1640    0.083011
1635    0.051823
Name: Normalised, Length: 305, dtype: float64

In [4]:
df_new= sorted_df.sort_values(by='Normalised', ascending=False).head(20)

In [5]:
df_new

,Dataset_Name,diffusion_ver,Adaptor,lora_rank,clipi,clipt,num_train_steps,no_of_images,learning_rate,output_path,with_prior_preservation,Normalised
721,clock,sdxl,lora,4,0.917466,0.878726,400,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.796192
1260,clock,sdxl,lora,16,0.940499,0.838190,400,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.778690
763,clock,sdxl,lora,4,0.919386,0.827990,1000,6,0.000100,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.747376
1344,clock,sdxl,krona,8,0.904031,0.838787,1000,6,0.000200,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.742817
1908,clock,sdxl,krona,4,0.988484,0.749868,500,6,0.000400,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.738351
1336,clock,sdxl,krona,8,0.932821,0.803517,800,6,0.000200,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.736339
1897,clock,sdxl,krona,4,0.921305,0.808319,1000,6,0.000200,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.729624
1921,clock,sdxl,krona,4,0.904031,0.825275,500,6,0.000700,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.729306
529,clock,sdxl,lora,8,0.925144,0.802358,1200,6,0.000020,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.727502
1049,clock,sdxl,lora,4,0.884837,0.825507,400,6,0.000050,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.710344
1521,clock,sdxl,lora,16,0.785029,0.922904,400,6,0.000010,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.707932
1879,clock,sdxl,krona,8,0.857965,0.848788,500,6,0.000900,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.706753
1375,clock,sdxl,lora,16,0.942418,0.763015,400,6,0.000050,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.705433
1914,clock,sdxl,krona,4,0.913628,0.790138,500,6,0.000600,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.703765
1118,clock,sdxl,lora,4,0.840691,0.861306,1200,6,0.000050,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.701997
413,clock,sdxl,krona,4,0.702495,0.999139,1000,6,0.000002,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.701634
1488,clock,sdxl,krona,8,0.884837,0.816698,500,6,0.000600,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.701534
173,clock,sdxl,krona,8,0.761996,0.938667,800,6,0.000050,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.700664
51,clock,sdxl,krona,8,0.698656,0.997417,400,6,0.000005,/home/btech/ayush.singh/outputs_sdxl/clock/kro...,False,1.696073
1149,clock,sdxl,lora,4,0.867562,0.827891,800,6,0.000020,/home/btech/ayush.singh/outputs_sdxl/clock/lor...,False,1.695453

krona_sdxl_8_0.0005_800_False

In [6]:
import pandas as pd
# Assuming you have the CSV data in a variable called "csv_data"
# If not, you can read it from a file using pd.read_csv('your_file_path.csv')
data = '/home/btech/ayush.singh/HSN/tune_diffusion/examples/dreambooth/data.csv'

# Create a DataFrame from the data
df = pd.read_csv(data)
print(df)

     Dataset_Name diffusion_ver Adaptor  lora_rank     clipi     clipt  \
0             cat          sdxl    lora          8  0.863281  0.314760
1             cat          sdxl   krona          8  0.799316  0.327174
2            dog6          sdxl   krona          8  0.753418  0.306680
3            dog2          sdxl   krona          8  0.731934  0.309954
4            dog6          sdxl    lora          8  0.831543  0.286351
...           ...           ...     ...        ...       ...       ...
2419          cat          sdxl    lora          4  0.874512  0.300223
2420          cat          sdxl    lora          4  0.618164  0.185242
2421          cat          sdxl    lora          4  0.885254  0.289145
2422          cat          sdxl    lora          4  0.597656  0.193359
2423          cat          sdxl    lora          8  0.870605  0.298941

      num_train_steps  no_of_images  learning_rate  \
0                 400             5         0.0001
1                 400             5         0.0001
2                 400             5         0.0001
3                 400             6         0.0001
4                 400             5         0.0001
...               ...           ...            ...
2419              500             5         0.0006
2420             1000             5         0.0006
2421              500             5         0.0007
2422             1000             5         0.0007
2423              500             5         0.0006

                                            output_path  \
0     /home/btech/ayush.singh/outputs_sdxl/cat/lora_...
1     /home/btech/ayush.singh/outputs_sdxl/cat/krona...
2     /home/btech/ayush.singh/outputs_sdxl/dog6/kron...
3     /home/btech/ayush.singh/outputs_sdxl/dog2/kron...
4     /home/btech/ayush.singh/outputs_sdxl/dog6/lora...
...                                                 ...
2419  /home/btech/ayush.singh/outputs_sdxl/cat/lora_...
2420  /home/btech/ayush.singh/outputs_sdxl/cat/lora_...
2421  /home/btech/ayush.singh/outputs_sdxl/cat/lora_...
2422  /home/btech/ayush.singh/outputs_sdxl/cat/lora_...
2423  /home/btech/ayush.singh/outputs_sdxl/cat/lora_...

      with_prior_preservation
0                       False
1                       False
2                       False
3                       False
4                       False
...                       ...
2419                    False
2420                    False
2421                    False
2422                    False
2423                    False

[2424 rows x 11 columns]

In [7]:
supersaiyan= 46
nisheetkaran = 30
backpack = 4 + 25
clock = 3 + 25
teapot = 5 + 25


dog2= 10 + 25
cat = 15 + 25
dog6 = 12 + 25

In [8]:
DatasetName = 'dog2'
model_type = 'sdxl'
Adaptor = 'lora'

type_ = 'lora'
dataset = dog2 
dataset_name= 'dog2'

In [9]:
import pandas as pd

# Define the dataset, model_type, and learning_rates as before

# learning_rates = [1.00E-06, 2.00E-06, 5.00E-06, 1.00E-05, 2.00E-05,0.00045, 5.00E-05,0.00055, 1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]
learning_rates = [1.00E-06, 2.00E-06, 5.00E-06, 1.00E-05, 2.00E-05, 5.00E-05, 1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]

# learning_rates = [1.00E-04, 5.00E-06, 1.00E-05, 5.00E-05, 5.00E-04]
num_train_steps_list = [400 , 500, 1000]

# learning_rates = [1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]
# num_train_steps_list = [400, 1000] 

# ss
# learning_rates = [1.00E-04, 5.00E-06, 1.00E-05, 5.00E-05, 5.00E-04]
# num_train_steps_list = [500, 1000, 1500, 2000]

# Create a list to store the final DataFrames for different rank types
final_results = []

# Define the different rank_type values to iterate over
rank_types = [4, 8]

# Assume 'df' is your original DataFrame containing the required data

for rank_type in rank_types:
    result_dfs = []

    for num_train_steps in num_train_steps_list:
        rank_condition = df['lora_rank'] == rank_type
        dataset_condition = df['Dataset_Name'] == DatasetName  
        sdxl_condition = df['diffusion_ver'] == model_type
        num_train_steps_condition = df['num_train_steps'] == num_train_steps
        adapter_ = df['Adaptor'] == Adaptor 
        filtered_df = df[rank_condition & dataset_condition & sdxl_condition & num_train_steps_condition & adapter_]

        clip_values = [None] * len(learning_rates)

        # Iterate over each row in the filtered DataFrame and extract 'clipi' and 'clipt' values
        for index, row in filtered_df.iterrows():
            lr_index = learning_rates.index(row['learning_rate'])
            # Merge 'clipi' and 'clipt' values into one column separated by a comma and rounded to three decimals
            clip_values[lr_index] = f"{row['clipi']:.3f},{row['clipt']:.3f}"

        table_data = {f'': clip_values}
        result_df = pd.DataFrame(table_data)

        result_dfs.append(result_df)

    # Concatenate the DataFrames for different num_train_steps
    final_result_df = pd.concat(result_dfs, axis=1)

    # Store the final_result_df in the final_results list for each rank_type
    final_results.append(final_result_df)
m = []
# Display the final merged DataFrames for different rank_type values
for rank_type, result_df in zip(rank_types, final_results):
    m.append(result_df.T)

In [10]:
m[0]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
,"0.715,0.312","0.708,0.310","0.714,0.311","0.729,0.309","0.761,0.306","0.795,0.299","0.806,0.291",None,None,None,"0.817,0.291",None,None,None,None,None
,"0.674,0.319",None,"0.688,0.318","0.708,0.312","0.732,0.306",None,"0.776,0.292","0.763,0.300","0.798,0.285","0.787,0.292","0.802,0.284","0.774,0.258","0.810,0.278","0.558,0.170","0.579,0.197","0.504,0.213"
,"0.708,0.310","0.710,0.309","0.743,0.307","0.771,0.303","0.794,0.294","0.804,0.289","0.812,0.279","0.815,0.272","0.815,0.276","0.819,0.273","0.839,0.274","0.647,0.233","0.584,0.196","0.625,0.222","0.560,0.196","0.546,0.199"

In [11]:
m[1]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
,"0.716,0.312","0.708,0.310","0.713,0.311","0.734,0.309","0.762,0.306","0.797,0.294",None,None,None,None,"0.828,0.280",None,None,None,None,None
,None,"0.683,0.319","0.688,0.317",None,"0.742,0.301",None,None,"0.792,0.286","0.801,0.287","0.808,0.283",None,"0.813,0.283","0.794,0.286","0.803,0.282","0.826,0.273","0.848,0.262"
,"0.705,0.310","0.712,0.310","0.742,0.308","0.770,0.305","0.795,0.298","0.815,0.289","0.828,0.283","0.821,0.257","0.839,0.247","0.844,0.245","0.862,0.259","0.849,0.238","0.861,0.256","0.872,0.242","0.853,0.247","0.867,0.243"

In [12]:
import pandas as pd


# Define the dataset, model_type, and learning_rates as before

# learning_rates = [1.00E-06, 2.00E-06, 5.00E-06, 1.00E-05, 2.00E-05,0.00045, 5.00E-05,0.00055, 1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]
learning_rates = [1.00E-06, 2.00E-06, 5.00E-06, 1.00E-05, 2.00E-05, 5.00E-05, 1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]

# learning_rates = [1.00E-04, 5.00E-06, 1.00E-05, 5.00E-05, 5.00E-04]
num_train_steps_list = [400 , 500, 1000]

# learning_rates = [1.00E-04, 2.00E-04, 3.00E-04, 4.00E-04,  5.00E-04, 6.00E-04, 7.00E-04, 8.00E-04, 9.00E-04, 1.00E-03]
# num_train_steps_list = [400, 1000] 

# Create a list to store the final DataFrames for different rank types
final_results = []

# Define the different rank_type values to iterate over
rank_types = [4, 8]

# Assume 'df' is your original DataFrame containing the required data

for rank_type in rank_types:
    result_dfs = []

    for num_train_steps in num_train_steps_list:
        rank_condition = df['lora_rank'] == rank_type
        dataset_condition = df['Dataset_Name'] == DatasetName  
        sdxl_condition = df['diffusion_ver'] == model_type
        num_train_steps_condition = df['num_train_steps'] == num_train_steps
        adapter_ = df['Adaptor'] == Adaptor 
        filtered_df = df[rank_condition & dataset_condition & sdxl_condition & num_train_steps_condition & adapter_]

        image_path = [None] * len(learning_rates)

        # Iterate over each row in the filtered DataFrame and extract 'clipi' and 'clipt' values
        for index, row in filtered_df.iterrows():
            lr_index = learning_rates.index(row['learning_rate'])
            # Merge 'clipi' and 'clipt' values into one column separated by a comma and rounded to three decimals
            image_path[lr_index] = f"{row['output_path']}/images"

        table_data = { f'': image_path}
        result_df = pd.DataFrame(table_data)

        result_dfs.append(result_df)

    # Concatenate the DataFrames for different num_train_steps
    final_result_df = pd.concat(result_dfs, axis=1)

    # Store the final_result_df in the final_results list for each rank_type
    final_results.append(final_result_df)
m = []
# Display the final merged DataFrames for different rank_type values
for rank_type, result_df in zip(rank_types, final_results):
    m.append(result_df.T)

In [13]:
df_1 = m[0]

In [14]:
first_row = df_1.iloc[0]
second_row = df_1.iloc[1]
third_row = df_1.iloc[2]
for i in range(len(second_row)):
    if second_row[i] == None:
        second_row[i] = first_row[i]
a = second_row.to_frame().T
b = third_row.to_frame().T
merged_df1 = pd.concat([a, b])

# Reset the index of the merged DataFrame
merged_df1.reset_index(drop=True, inplace=True)

In [15]:
df_2 = m[1]

In [16]:
first_row = df_2.iloc[0]
second_row = df_2.iloc[1]
third_row = df_2.iloc[2]
for i in range(len(second_row)):
    if second_row[i] == None:
        second_row[i] = first_row[i]
a = second_row.to_frame().T
b = third_row.to_frame().T
merged_df2 = pd.concat([a, b])

# Reset the index of the merged DataFrame
merged_df2.reset_index(drop=True, inplace=True)

In [17]:
merged_df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...
1,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...

In [18]:
merged_df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,None,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...
1,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...

In [19]:
m= pd.concat([merged_df1,merged_df2])

In [20]:
m

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...
1,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...
0,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,None,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...
1,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...,/home/btech/ayush.singh/outputs_sdxl/dog2/lora...

In [21]:
for x in range(1):
    for y in range(1,dataset+1):
        flattened_list = m.values.flatten()
        # Step 3: Replace None values with the desired string
        desired_string = "N/A"  # Replace 'N/A' with any string you want to append
        final_list = [str(val) if val is not None else desired_string for val in flattened_list]
        folder_paths = list(final_list)

        from PIL import Image
        import os
        from PIL import Image, ImageDraw, ImageFont
        iteration = 4
        no_of_lr = 16

        def load_images_from_folders(folder_paths):
            images = []
            for folder_path in folder_paths:
                img_path = os.path.join(folder_path, f"image_{y}.jpg")
                print(img_path)
                if os.path.exists(img_path):
                    try:
                        img = Image.open(img_path)
                        images.append(img)
                    except:
                        print(f"Could not load image from {img_path}")
                else:
                    width, height = images[0].size if images else (100, 100)  
                    blank_image = Image.new('RGB', (width, height), (255, 255, 255))
                    images.append(blank_image)
            return images


        all_images = load_images_from_folders(folder_paths)

        if len(all_images) < iteration*no_of_lr:
            print("Warning: Fewer than 12 images found. Filling with blank images.")
            while len(all_images) < iteration*no_of_lr:
                width, height = all_images[0].size if all_images else (100, 100)  
                blank_image = Image.new('RGB', (width, height), (255, 255, 255))
                all_images.append(blank_image)

        width, height = all_images[0].size  
        combined_image = Image.new('RGB', (width * no_of_lr, height * iteration))
        # Increase the text size by 10 times
        font_size = 50
        font = ImageFont.load_default()  # Using the default system font
        draw = ImageDraw.Draw(combined_image)

        for i in range(iteration):
            for j in range(no_of_lr):
                index = i * no_of_lr + j
                combined_image.paste(all_images[index], (j * width, i * height))
                text = f"Learning rate: {learning_rates[j]}"
                text_width, text_height = draw.textsize(text, font=font)
                text_position = (j * width, i * height + height - text_height)
                
                # Draw the learning rate text on the image
                draw.text(text_position, text, font=font, fill=(0, 0, 0))

        folder_path = f"./images/{type_}/{dataset_name}/{x}/"

        # Check if the folder exists, and create it if it doesn't
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)

        combined_image.show()
        combined_image.save(f"./images/{type_}/{dataset_name}/{x}/prompt{y}.png")
        print("done")

/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_1.jpg
N/A/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_1.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_1.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_2.jpg
N/A/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_2.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_2.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_3.jpg
N/A/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_3.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_3.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_4.jpg
N/A/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_4.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_4.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_5.jpg
N/A/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_5.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_5.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_6.jpg
N/A/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_6.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_6.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_7.jpg
N/A/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_7.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_7.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_8.jpg
N/A/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_8.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_8.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_9.jpg
N/A/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_9.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_9.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_10.jpg
N/A/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_10.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_10.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_11.jpg
N/A/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_11.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_11.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_12.jpg
N/A/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_12.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_12.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_13.jpg
N/A/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_13.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_13.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_14.jpg
N/A/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_14.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_14.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_15.jpg
N/A/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_15.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_15.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_16.jpg
N/A/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_16.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_16.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_17.jpg
N/A/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_17.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_17.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_18.jpg
N/A/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_18.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_18.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_19.jpg
N/A/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_19.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_19.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_20.jpg
N/A/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_20.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_20.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_21.jpg
N/A/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_21.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_21.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_22.jpg
N/A/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_22.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_22.jpg
done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_23.jpg
N/A/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_23.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_23.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_24.jpg
N/A/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_24.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_24.jpg
done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_25.jpg
N/A/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_25.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_25.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_26.jpg
N/A/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_26.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_26.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_27.jpg
N/A/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_27.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_27.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_28.jpg
N/A/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_28.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_28.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_29.jpg
N/A/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_29.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_29.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_30.jpg
N/A/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_30.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_30.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_31.jpg
N/A/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_31.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_31.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_32.jpg
N/A/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_32.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_32.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_33.jpg
N/A/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_33.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_33.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_34.jpg
N/A/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_34.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_34.jpg

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)

done
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_400_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_400_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_1e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_2e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_5e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0001_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0002_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0003_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0004_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0005_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0006_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0007_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0008_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.0009_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_4_0.001_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_400_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_400_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_400_False/images/image_35.jpg
N/A/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_400_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_500_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-06_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_1e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_2e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_5e-05_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0001_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0002_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0003_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0004_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0005_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0006_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0007_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0008_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.0009_1000_False/images/image_35.jpg
/home/btech/ayush.singh/outputs_sdxl/dog2/lora_sdxl_8_0.001_1000_False/images/image_35.jpg
done

/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)
/tmp/ipykernel_3952909/2913398287.py:54: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(text, font=font)